USE [master]
GO

/****** Object:  Database [Netflix]    Script Date: 24/02/2018 10:24:11 a.m. ******/
DROP DATABASE [Netflix]
GO

/****** Object:  Database [Netflix]    Script Date: 24/02/2018 10:24:11 a.m. ******/
CREATE DATABASE [Netflix]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Netflix', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Netflix.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Netflix_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Netflix_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Netflix] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Netflix].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Netflix] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Netflix] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Netflix] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Netflix] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Netflix] SET ARITHABORT OFF 
GO

ALTER DATABASE [Netflix] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Netflix] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Netflix] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Netflix] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Netflix] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Netflix] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Netflix] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Netflix] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Netflix] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Netflix] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Netflix] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Netflix] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Netflix] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Netflix] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Netflix] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Netflix] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Netflix] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Netflix] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Netflix] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Netflix] SET  MULTI_USER 
GO

ALTER DATABASE [Netflix] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Netflix] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Netflix] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Netflix] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Netflix] SET  READ_WRITE 
GO


