USE [master]
GO

/****** Object:  Database [netflix]    Script Date: 04/30/2018 21:10:34 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'netflix')
DROP DATABASE [netflix]
GO

USE [master]
GO

/****** Object:  Database [netflix]    Script Date: 04/30/2018 21:10:34 ******/
CREATE DATABASE [netflix] ON  PRIMARY 
( NAME = N'netflix', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\netflix.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'netflix_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\netflix_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [netflix] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [netflix].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [netflix] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [netflix] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [netflix] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [netflix] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [netflix] SET ARITHABORT OFF 
GO

ALTER DATABASE [netflix] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [netflix] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [netflix] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [netflix] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [netflix] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [netflix] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [netflix] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [netflix] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [netflix] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [netflix] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [netflix] SET  DISABLE_BROKER 
GO

ALTER DATABASE [netflix] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [netflix] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [netflix] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [netflix] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [netflix] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [netflix] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [netflix] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [netflix] SET  READ_WRITE 
GO

ALTER DATABASE [netflix] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [netflix] SET  MULTI_USER 
GO

ALTER DATABASE [netflix] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [netflix] SET DB_CHAINING OFF 
GO

